import 'package:flutter/material.dart';
import 'package:world_time_app/services/world_time.dart';

class SelectLocation extends StatefulWidget {
  @override
  _SelectLocationState createState() => _SelectLocationState();
}

class _SelectLocationState extends State<SelectLocation> {

  List<WorldTime> locations = [
    WorldTime(url: 'Africa/Abidjan', location: 'Africa - Abidjan'),
    WorldTime(url: 'Africa/Accra', location: 'Africa - Accra'),
    WorldTime(url: 'Africa/Algiers', location: 'Africa - Algiers'),
    WorldTime(url: 'Africa/Bissau', location: 'Africa - Bissau'),
    WorldTime(url: 'Africa/Cairo', location: 'Africa - Cairo'),
    WorldTime(url: 'Africa/Casablanca', location: 'Africa - Casablanca'),
    WorldTime(url: 'Africa/Ceuta', location: 'Africa - Ceuta'),
    WorldTime(url: 'Africa/El_Aaiun', location: 'Africa - El_Aaiun'),
    WorldTime(url: 'Africa/Johannesburg', location: 'Africa - Johannesburg'),
    WorldTime(url: 'Africa/Juba', location: 'Africa - Juba'),
    WorldTime(url: 'Africa/Khartoum', location: 'Africa - Khartoum'),
    WorldTime(url: 'Africa/Lagos', location: 'Africa - Lagos'),
    WorldTime(url: 'Africa/Maputo', location: 'Africa - Maputo'),
    WorldTime(url: 'Africa/Monrovia', location: 'Africa - Monrovia'),
    WorldTime(url: 'Africa/Nairobi', location: 'Africa - Nairobi'),
    WorldTime(url: 'Africa/Ndjamena', location: 'Africa - Ndjamena'),
    WorldTime(url: 'Africa/Sao_Tome', location: 'Africa - Sao Tome'),
    WorldTime(url: 'Africa/Tripoli', location: 'Africa - Tripoli'),
    WorldTime(url: 'Africa/Tunis', location: 'Africa - Tunis'),
    WorldTime(url: 'Africa/Windhoek', location: 'Africa - Windhoek'),
    WorldTime(url: 'America/Adak', location: 'America - Adak'),
    WorldTime(url: 'America/Anchorage', location: 'America - Anchorage'),
    WorldTime(url: 'America/Araguaina', location: 'America - Araguaina'),
    WorldTime(url: 'America/Argentina/Buenos_Aires', location: 'Argentina - Buenos Aires'),
    WorldTime(url: 'America/Argentina/Catamarca', location: 'Argentina - Catamarca'),
    WorldTime(url: 'America/Argentina/Cordoba', location: 'Argentina - Cordoba'),
    WorldTime(url: 'America/Argentina/Jujuy', location: 'Argentina - Jujuy'),
    WorldTime(url: 'America/Argentina/La_Rioja', location: 'Argentina - La Rioja'),
    WorldTime(url: 'America/Argentina/Mendoza', location: 'Argentina - Mendoza'),
    WorldTime(url: 'America/Argentina/Rio_Gallegos', location: 'Argentina - Rio Gallegos'),
    WorldTime(url: 'America/Argentina/Salta', location: 'Argentina - Salta'),
    WorldTime(url: 'America/Argentina/San_Juan', location: 'Argentina - San Juan'),
    WorldTime(url: 'America/Argentina/San_Luis', location: 'Argentina - San Luis'),
    WorldTime(url: 'America/Argentina/Tucuman', location: 'Argentina - Tucuman'),
    WorldTime(url: 'America/Argentina/Ushuaia', location: 'Argentina - Ushuaia'),
    WorldTime(url: 'America/Asuncion', location: 'America - Asuncion'),
    WorldTime(url: 'America/Atikokan', location: 'America - Atikokan'),
    WorldTime(url: 'America/Bahia', location: 'America - Bahia'),
    WorldTime(url: 'America/Bahia_Banderas', location: 'America - Bahia Banderas'),
    WorldTime(url: 'America/Barbados', location: 'America - Barbado'),
    WorldTime(url: 'America/Belem', location: 'America - Belem'),
    WorldTime(url: 'America/Belize', location: 'America - Belize'),
    WorldTime(url: 'America/Blanc-Sablon', location: 'America - Blanc-Sablon'),
    WorldTime(url: 'America/Boa_Vista', location: 'America - Boa Vista'),
    WorldTime(url: 'America/Bogota', location: 'America - Bogota'),
    WorldTime(url: 'America/Boise', location: 'America - Boise'),
    WorldTime(url: 'America/Cambridge_Bay', location: 'America - Cambridge Bay'),
    WorldTime(url: 'America/Campo_Grande', location: 'America - Campo Grande'),
    WorldTime(url: 'America/Cancun', location: 'America - Cancun'),
    WorldTime(url: 'America/Caracas', location: 'America - Caracas'),
    WorldTime(url: 'America/Cayenne', location: 'America - Cayenne'),
    WorldTime(url: 'America/Chicago', location: 'America - Chicago'),
    WorldTime(url: 'America/Chihuahua', location: 'America - Chihuahua'),
    WorldTime(url: 'America/Costa_Rica', location: 'America - Costa Rica'),
    WorldTime(url: 'America/Creston', location: 'America - Creston'),
    WorldTime(url: 'America/Cuiaba', location: 'America - Cuiaba'),
    WorldTime(url: 'America/Curacao', location: 'America - Curacao'),
    WorldTime(url: 'America/Danmarkshavn', location: 'America - Danmarkshavn'),
    WorldTime(url: 'America/Dawson', location: 'America - Dawson'),
    WorldTime(url: 'America/Dawson_Creek', location: 'America - Dawson Creek'),
    WorldTime(url: 'America/Denver', location: 'America - Denver'),
    WorldTime(url: 'America/Detroit', location: 'America - Detroit'),
    WorldTime(url: 'America/Edmonton', location: 'America - Edmonton'),
    WorldTime(url: 'America/Eirunepe', location: 'America - Eirunepe'),
    WorldTime(url: 'America/El_Salvador', location: 'America - El Salvador'),
    WorldTime(url: 'America/Fort_Nelson', location: 'America - Fort Nelson'),
    WorldTime(url: 'America/Fortaleza', location: 'America - Fortaleza'),
    WorldTime(url: 'America/Glace_Bay', location: 'America - Glace Bay'),
    WorldTime(url: 'America/Goose_Bay', location: 'America - Goose Bay'),
    WorldTime(url: 'America/Grand_Turk', location: 'America - Grand Turk'),
    WorldTime(url: 'America/Guatemala', location: 'America - Guatemala'),
    WorldTime(url: 'America/Guayaquil', location: 'America - Guayaquil'),
    WorldTime(url: 'America/Guyana', location: 'America - Guyana'),
    WorldTime(url: 'America/Halifax', location: 'America - Halifax'),
    WorldTime(url: 'America/Havana', location: 'America - Havana'),
    WorldTime(url: 'America/Hermosillo', location: 'America - Hermosillo'),
    WorldTime(url: 'America/Indiana/Indianapolis', location: 'Indiana - Indianapolis'),
    WorldTime(url: 'America/Indiana/Knox', location: 'Indiana - Knox'),
    WorldTime(url: 'America/Indiana/Marengo', location: 'Indiana - Marengo'),
    WorldTime(url: 'America/Indiana/Petersburg', location: 'Indiana - Petersburg'),
    WorldTime(url: 'America/Indiana/Tell_City', location: 'Indiana - Tell_City'),
    WorldTime(url: 'America/Indiana/Vevay', location: 'Indiana - Vevay'),
    WorldTime(url: 'America/Indiana/Vincennes', location: 'Indiana - Vincennes'),
    WorldTime(url: 'America/Indiana/Winamac', location: 'Indiana - Winamac'),
    WorldTime(url: 'America/Inuvik', location: 'America - Inuvik'),
    WorldTime(url: 'America/Iqaluit', location: 'America - Iqaluit'),
    WorldTime(url: 'America/Jamaica', location: 'America - Jamaica'),
    WorldTime(url: 'America/Juneau', location: 'America - Juneau'),
    WorldTime(url: 'America/Kentucky/Louisville', location: 'Kentucky - Louisville'),
    WorldTime(url: 'America/Kentucky/Monticello', location: 'Kentucky - Monticello'),
    WorldTime(url: 'America/La_Paz', location: 'America - La Paz'),
    WorldTime(url: 'America/Lima', location: 'America - Lima'),
    WorldTime(url: 'America/Los_Angeles', location: 'America - Los Angeles'),
    WorldTime(url: 'America/Maceio', location: 'America - Maceio'),
    WorldTime(url: 'America/Managua', location: 'America - Managua'),
    WorldTime(url: 'America/Manaus', location: 'America - Manaus'),
    WorldTime(url: 'America/Martinique', location: 'America - Martinique'),
    WorldTime(url: 'America/Matamoros', location: 'America - Matamoros'),
    WorldTime(url: 'America/Mazatlan', location: 'America - Mazatlan'),
    WorldTime(url: 'America/Menominee', location: 'America - Menominee'),
    WorldTime(url: 'America/Merida', location: 'America - Merida'),
    WorldTime(url: 'America/Metlakatla', location: 'America - Metlakatla'),
    WorldTime(url: 'America/Mexico_City', location: 'America - Mexico City'),
    WorldTime(url: 'America/Miquelon', location: 'America - Miquelon'),
    WorldTime(url: 'America/Moncton', location: 'America - Moncton'),
    WorldTime(url: 'America/Monterrey', location: 'America - Monterrey'),
    WorldTime(url: 'America/Montevideo', location: 'America - Montevideo'),
    WorldTime(url: 'America/Nassau', location: 'America - Nassau'),
    WorldTime(url: 'America/New_York', location: 'America - New York'),
    WorldTime(url: 'America/Nipigon', location: 'America - Nipigon'),
    WorldTime(url: 'America/Nome', location: 'America - Nome'),
    WorldTime(url: 'America/Noronha', location: 'America - Noronha'),
    WorldTime(url: 'America/North_Dakota/Beulah', location: 'North Dakota - Beulah'),
    WorldTime(url: 'America/North_Dakota/Center', location: 'North Dakota - Center'),
    WorldTime(url: 'America/North_Dakota/New_Salem', location: 'North Dakota - New Salem'),
    WorldTime(url: 'America/Nuuk', location: 'America - Nuuk'),
    WorldTime(url: 'America/Ojinaga', location: 'America - Ojinaga'),
    WorldTime(url: 'America/Panama', location: 'America - Panama'),
    WorldTime(url: 'America/Pangnirtung', location: 'America - Pangnirtung'),
    WorldTime(url: 'America/Paramaribo', location: 'America - Paramaribo'),
    WorldTime(url: 'America/Phoenix', location: 'America - Phoenix'),
    WorldTime(url: 'America/Port-au-Prince', location: 'America - Port-au-Prince'),
    WorldTime(url: 'America/Port_of_Spain', location: 'America - Port of Spain'),
    WorldTime(url: 'America/Porto_Velho', location: 'America - Porto Velho'),
    WorldTime(url: 'America/Puerto_Rico', location: 'America - Puerto Rico'),
    WorldTime(url: 'America/Punta_Arenas', location: 'America - Punta Arenas'),
    WorldTime(url: 'America/Rainy_River', location: 'America - Rainy River'),
    WorldTime(url: 'America/Rankin_Inlet', location: 'America - Rankin Inlet'),
    WorldTime(url: 'America/Recife', location: 'America - Recife'),
    WorldTime(url: 'America/Regina', location: 'America - Regina'),
    WorldTime(url: 'America/Resolute', location: 'America - Resolute'),
    WorldTime(url: 'America/Rio_Branco', location: 'America - Rio Branco'),
    WorldTime(url: 'America/Santarem', location: 'America - Santarem'),
    WorldTime(url: 'America/Santiago', location: 'America - Santiago'),
    WorldTime(url: 'America/Santo_Domingo', location: 'America - Santo Domingo'),
    WorldTime(url: 'America/Sao_Paulo', location: 'America - Sao Paulo'),
    WorldTime(url: 'America/Scoresbysund', location: 'America - Scoresbysund'),
    WorldTime(url: 'America/Sitka', location: 'America - Sitka'),
    WorldTime(url: 'America/St_Johns', location: 'America - St Johns'),
    WorldTime(url: 'America/Swift_Current', location: 'America - Swift Current'),
    WorldTime(url: 'America/Tegucigalpa', location: 'America - Tegucigalpa'),
    WorldTime(url: 'America/Thule', location: 'America - Thule'),
    WorldTime(url: 'America/Thunder_Bay', location: 'America - Thunder Bay'),
    WorldTime(url: 'America/Tijuana', location: 'America - Tijuana'),
    WorldTime(url: 'America/Toronto', location: 'America - Toronto'),
    WorldTime(url: 'America/Vancouver', location: 'America - Vancouver'),
    WorldTime(url: 'America/Whitehorse', location: 'America - Whitehorse'),
    WorldTime(url: 'America/Winnipeg', location: 'America - Winnipeg'),
    WorldTime(url: 'America/Yakutat', location: 'America - Yakutat'),
    WorldTime(url: 'America/Yellowknife', location: 'America - Yellowknife'),
    WorldTime(url: 'Antarctica/Casey', location: 'Antarctica - Casey'),
    WorldTime(url: 'Antarctica/Davis', location: 'Antarctica - Davis'),
    WorldTime(url: 'Antarctica/DumontDUrville', location: 'Antarctica - DumontDUrville'),
    WorldTime(url: 'Antarctica/Macquarie', location: 'Antarctica - Macquarie'),
    WorldTime(url: 'Antarctica/Mawson', location: 'Antarctica - Mawson'),
    WorldTime(url: 'Antarctica/Palmer', location: 'Antarctica - Palmer'),
    WorldTime(url: 'Antarctica/Rothera', location: 'Antarctica - Rothera'),
    WorldTime(url: 'Antarctica/Syowa', location: 'Antarctica - Syowa'),
    WorldTime(url: 'Antarctica/Troll', location: 'Antarctica - Troll'),
    WorldTime(url: 'Antarctica/Vostok', location: 'Antarctica - Vostok'),
    WorldTime(url: 'Asia/Almaty', location: 'Asia - Almaty'),
    WorldTime(url: 'Asia/Amman', location: 'Asia - Amman'),
    WorldTime(url: 'Asia/Anadyr', location: 'Asia - Anadyr'),
    WorldTime(url: 'Asia/Aqtau', location: 'Asia - Aqtau'),
    WorldTime(url: 'Asia/Aqtobe', location: 'Asia - Aqtobe'),
    WorldTime(url: 'Asia/Ashgabat', location: 'Asia - Ashgabat'),
    WorldTime(url: 'Asia/Atyrau', location: 'Asia - Atyrau'),
    WorldTime(url: 'Asia/Baghdad', location: 'Asia - Baghdad'),
    WorldTime(url: 'Asia/Baku', location: 'Asia - Baku'),
    WorldTime(url: 'Asia/Bangkok', location: 'Asia - Bangkok'),
    WorldTime(url: 'Asia/Barnaul', location: 'Asia - Barnaul'),
    WorldTime(url: 'Asia/Beirut', location: 'Asia - Beirut'),
    WorldTime(url: 'Asia/Bishkek', location: 'Asia - Bishkek'),
    WorldTime(url: 'Asia/Brunei', location: 'Asia - Brunei'),
    WorldTime(url: 'Asia/Chita', location: 'Asia - Chita'),
    WorldTime(url: 'Asia/Choibalsan', location: 'Asia - Choibalsan'),
    WorldTime(url: 'Asia/Colombo', location: 'Asia - Colombo'),
    WorldTime(url: 'Asia/Damascus', location: 'Asia - Damascus'),
    WorldTime(url: 'Asia/Dhaka', location: 'Asia - Dhaka'),
    WorldTime(url: 'Asia/Dili', location: 'Asia - Dili'),
    WorldTime(url: 'Asia/Dubai', location: 'Asia - Dubai'),
    WorldTime(url: 'Asia/Dushanbe', location: 'Asia - Dushanbe'),
    WorldTime(url: 'Asia/Famagusta', location: 'Asia - Famagusta'),
    WorldTime(url: 'Asia/Gaza', location: 'Asia - Gaza'),
    WorldTime(url: 'Asia/Hebron', location: 'Asia - Hebron'),
    WorldTime(url: 'Asia/Ho_Chi_Minh', location: 'Asia - Ho Chi Minh'),
    WorldTime(url: 'Asia/Hong_Kong', location: 'Asia - Hong Kong'),
    WorldTime(url: 'Asia/Hovd', location: 'Asia - Hovd'),
    WorldTime(url: 'Asia/Irkutsk', location: 'Asia - Irkutsk'),
    WorldTime(url: 'Asia/Jakarta', location: 'Asia - Jakarta'),
    WorldTime(url: 'Asia/Jayapura', location: 'Asia - Jayapura'),
    WorldTime(url: 'Asia/Jerusalem', location: 'Asia - Jerusalem'),
    WorldTime(url: 'Asia/Kabul', location: 'Asia - Kabul'),
    WorldTime(url: 'Asia/Kamchatka', location: 'Asia - Kamchatka'),
    WorldTime(url: 'Asia/Karachi', location: 'Asia - Karachi'),
    WorldTime(url: 'Asia/Kathmandu', location: 'Asia - Kathmandu'),
    WorldTime(url: 'Asia/Khandyga', location: 'Asia - Khandyga'),
    WorldTime(url: 'Asia/Kolkata', location: 'Asia - Kolkata'),
    WorldTime(url: 'Asia/Krasnoyarsk', location: 'Asia - Krasnoyarsk'),
    WorldTime(url: 'Asia/Kuala_Lumpur', location: 'Asia - Kuala_Lumpur'),
    WorldTime(url: 'Asia/Kuching', location: 'Asia - Kuching'),
    WorldTime(url: 'Asia/Macau', location: 'Asia - Macau'),
    WorldTime(url: 'Asia/Magadan', location: 'Asia - Magadan'),
    WorldTime(url: 'Asia/Makassar', location: 'Asia - Makassar'),
    WorldTime(url: 'Asia/Manila', location: 'Asia - Manila'),
    WorldTime(url: 'Asia/Nicosia', location: 'Asia - Nicosia'),
    WorldTime(url: 'Asia/Novokuznetsk', location: 'Asia - Novokuznetsk'),
    WorldTime(url: 'Asia/Novosibirsk', location: 'Asia - Novosibirsk'),
    WorldTime(url: 'Asia/Omsk', location: 'Asia - Omsk'),
    WorldTime(url: 'Asia/Oral', location: 'Asia - Ora'),
    WorldTime(url: 'Asia/Pontianak', location: 'Asia - Pontianak'),
    WorldTime(url: 'Asia/Pyongyang', location: 'Asia - Pyongyang'),
    WorldTime(url: 'Asia/Qatar', location: 'Asia - Qatar'),
    WorldTime(url: 'Asia/Qostanay', location: 'Asia - Qostanay'),
    WorldTime(url: 'Asia/Qyzylorda', location: 'Asia - Qyzylorda'),
    WorldTime(url: 'Asia/Riyadh', location: 'Asia - Riyadh'),
    WorldTime(url: 'Asia/Sakhalin', location: 'Asia - Sakhalin'),
    WorldTime(url: 'Asia/Samarkand', location: 'Asia - Samarkand'),
    WorldTime(url: 'Asia/Seoul', location: 'Asia - Seoul'),
    WorldTime(url: 'Asia/Shanghai', location: 'Asia - Shanghai'),
    WorldTime(url: 'Asia/Singapore', location: 'Asia - Singapore'),
    WorldTime(url: 'Asia/Srednekolymsk', location: 'Asia - Srednekolymsk'),
    WorldTime(url: 'Asia/Taipei', location: 'Asia - Taipei'),
    WorldTime(url: 'Asia/Tashkent', location: 'Asia - Tashkent'),
    WorldTime(url: 'Asia/Tbilisi', location: 'Asia - Tbilisi'),
    WorldTime(url: 'Asia/Tehran', location: 'Asia - Tehran'),
    WorldTime(url: 'Asia/Thimphu', location: 'Asia - Thimphu'),
    WorldTime(url: 'Asia/Tokyo', location: 'Asia - Tokyo'),
    WorldTime(url: 'Asia/Tomsk', location: 'Asia - Tomsk'),
    WorldTime(url: 'Asia/Ulaanbaatar', location: 'Asia - Ulaanbaatar'),
    WorldTime(url: 'Asia/Urumqi', location: 'Asia - Urumqi'),
    WorldTime(url: 'Asia/Ust-Nera', location: 'Asia - Ust-Nera'),
    WorldTime(url: 'Asia/Vladivostok', location: 'Asia - Vladivostok'),
    WorldTime(url: 'Asia/Yakutsk', location: 'Asia - Yakutsk'),
    WorldTime(url: 'Asia/Yangon', location: 'Asia - Yangon'),
    WorldTime(url: 'Asia/Yekaterinburg', location: 'Asia - Yekaterinburg'),
    WorldTime(url: 'Asia/Yerevan', location: 'Asia - Yerevan'),
    WorldTime(url: 'Atlantic/Azores', location: 'Atlantic - Azores'),
    WorldTime(url: 'Atlantic/Bermuda', location: 'Atlantic - Bermuda'),
    WorldTime(url: 'Atlantic/Canary', location: 'Atlantic - Canary'),
    WorldTime(url: 'Atlantic/Cape_Verde', location: 'Atlantic - Cape Verde'),
    WorldTime(url: 'Atlantic/Faroe', location: 'Atlantic - Faroe'),
    WorldTime(url: 'Atlantic/Madeira', location: 'Atlantic - Madeira'),
    WorldTime(url: 'Atlantic/Reykjavik', location: 'Atlantic - Reykjavik'),
    WorldTime(url: 'Atlantic/South_Georgia', location: 'Atlantic - South Georgia'),
    WorldTime(url: 'Atlantic/Stanley', location: 'Atlantic - Stanley'),
    WorldTime(url: 'Australia/Adelaide', location: 'Australia - Adelaide'),
    WorldTime(url: 'Australia/Brisbane', location: 'Australia - Brisbane'),
    WorldTime(url: 'Australia/Broken_Hill', location: 'Australia - Broken Hill'),
    WorldTime(url: 'Australia/Darwin', location: 'Australia - Darwin'),
    WorldTime(url: 'Australia/Eucla', location: 'Australia - Eucla'),
    WorldTime(url: 'Australia/Hobart', location: 'Australia - Hobart'),
    WorldTime(url: 'Australia/Lindeman', location: 'Australia - Lindeman'),
    WorldTime(url: 'Australia/Lord_Howe', location: 'Australia - Lord Howe'),
    WorldTime(url: 'Australia/Melbourne', location: 'Australia - Melbourne'),
    WorldTime(url: 'Australia/Perth', location: 'Australia - Perth'),
    WorldTime(url: 'Australia/Sydney', location: 'Australia - Sydney'),
    WorldTime(url: 'Europe/Amsterdam', location: 'Europe - Amsterdam'),
    WorldTime(url: 'Europe/Andorra', location: 'Europe - Andorra'),
    WorldTime(url: 'Europe/Astrakhan', location: 'Europe - Astrakhan'),
    WorldTime(url: 'Europe/Athens', location: 'Europe - Athens'),
    WorldTime(url: 'Europe/Belgrade', location: 'Europe - Belgrade'),
    WorldTime(url: 'Europe/Berlin', location: 'Europe - Berlin'),
    WorldTime(url: 'Europe/Brussels', location: 'Europe - Brussels'),
    WorldTime(url: 'Europe/Bucharest', location: 'Europe - Bucharest'),
    WorldTime(url: 'Europe/Bucharest', location: 'Europe - Bucharest'),
    WorldTime(url: 'Europe/Budapest', location: 'Europe - Budapest'),
    WorldTime(url: 'Europe/Chisinau', location: 'Europe - Chisinau'),
    WorldTime(url: 'Europe/Copenhagen', location: 'Europe - Copenhagen'),
    WorldTime(url: 'Europe/Dublin', location: 'Europe - Dublin'),
    WorldTime(url: 'Europe/Gibraltar', location: 'Europe - Gibraltar'),
    WorldTime(url: 'Europe/Helsinki', location: 'Europe - Helsinki'),
    WorldTime(url: 'Europe/Istanbul', location: 'Europe - Istanbul'),
    WorldTime(url: 'Europe/Kaliningrad', location: 'Europe - Kaliningrad'),
    WorldTime(url: 'Europe/Kiev', location: 'Europe - Kiev'),
    WorldTime(url: 'Europe/Kirov', location: 'Europe - Kirov'),
    WorldTime(url: 'Europe/Lisbon', location: 'Europe - Lisbon'),
    WorldTime(url: 'Europe/London', location: 'Europe - London'),
    WorldTime(url: 'Europe/Luxembourg', location: 'Europe - Luxembourg'),
    WorldTime(url: 'Europe/Madrid', location: 'Europe - Madrid'),
    WorldTime(url: 'Europe/Malta', location: 'Europe - Malta'),
    WorldTime(url: 'Europe/Minsk', location: 'Europe - Minsk'),
    WorldTime(url: 'Europe/Monaco', location: 'Europe - Monaco'),
    WorldTime(url: 'Europe/Moscow', location: 'Europe - Moscow'),
    WorldTime(url: 'Europe/Oslo', location: 'Europe - Oslo'),
    WorldTime(url: 'Europe/Paris', location: 'Europe - Paris'),
    WorldTime(url: 'Europe/Prague', location: 'Europe - Prague'),
    WorldTime(url: 'Europe/Riga', location: 'Europe - Riga'),
    WorldTime(url: 'Europe/Rome', location: 'Europe - Rome'),
    WorldTime(url: 'Europe/Samara', location: 'Europe - Samara'),
    WorldTime(url: 'Europe/Saratov', location: 'Europe - Saratov'),
    WorldTime(url: 'Europe/Simferopol', location: 'Europe - Simferopol'),
    WorldTime(url: 'Europe/Sofia', location: 'Europe - Sofia'),
    WorldTime(url: 'Europe/Stockholm', location: 'Europe - Stockholm'),
    WorldTime(url: 'Europe/Tallinn', location: 'Europe - Tallinn'),
    WorldTime(url: 'Europe/Tirane', location: 'Europe - Tirane'),
    WorldTime(url: 'Europe/Ulyanovsk', location: 'Europe - Ulyanovsk'),
    WorldTime(url: 'Europe/Uzhgorod', location: 'Europe - Uzhgorod'),
    WorldTime(url: 'Europe/Vienna', location: 'Europe - Vienna'),
    WorldTime(url: 'Europe/Vilnius', location: 'Europe - Vilnius'),
    WorldTime(url: 'Europe/Volgograd', location: 'Europe - Volgograd'),
    WorldTime(url: 'Europe/Warsaw', location: 'Europe - Warsaw'),
    WorldTime(url: 'Europe/Zaporozhye', location: 'Europe - Zaporozhye'),
    WorldTime(url: 'Europe/Zurich', location: 'Europe - Zurich'),
    WorldTime(url: 'Indian/Chagos', location: 'Indian - Chagos'),
    WorldTime(url: 'Indian/Christmas', location: 'Indian - Christmas'),
    WorldTime(url: 'Indian/Cocos', location: 'Indian - Cocos'),
    WorldTime(url: 'Indian/Kerguelen', location: 'Indian - Kerguelen'),
    WorldTime(url: 'Indian/Mahe', location: 'Indian - Mahe'),
    WorldTime(url: 'Indian/Maldives', location: 'Indian - Maldives'),
    WorldTime(url: 'Indian/Mauritius', location: 'Indian - Mauritius'),
    WorldTime(url: 'Indian/Reunion', location: 'Indian - Reunion'),
    WorldTime(url: 'Pacific/Apia', location: 'Pacific - Apia'),
    WorldTime(url: 'Pacific/Auckland', location: 'Pacific - Auckland'),
    WorldTime(url: 'Pacific/Bougainville', location: 'Pacific - Bougainville'),
    WorldTime(url: 'Pacific/Chatham', location: 'Pacific - Chatham'),
    WorldTime(url: 'Pacific/Chuuk', location: 'Pacific - Chuuk'),
    WorldTime(url: 'Pacific/Easter', location: 'Pacific - Easter'),
    WorldTime(url: 'Pacific/Efate', location: 'Pacific - Efate'),
    WorldTime(url: 'Pacific/Enderbury', location: 'Pacific - Enderbury'),
    WorldTime(url: 'Pacific/Fakaofo', location: 'Pacific - Fakaofo'),
    WorldTime(url: 'Pacific/Fiji', location: 'Pacific - Fiji'),
    WorldTime(url: 'Pacific/Funafuti', location: 'Pacific - Funafuti'),
    WorldTime(url: 'Pacific/Galapagos', location: 'Pacific - Galapagos'),
    WorldTime(url: 'Pacific/Gambier', location: 'Pacific - Gambier'),
    WorldTime(url: 'Pacific/Guadalcanal', location: 'Pacific - Guadalcanal'),
    WorldTime(url: 'Pacific/Guam', location: 'Pacific - Guam'),
    WorldTime(url: 'Pacific/Honolulu', location: 'Pacific - Honolulu'),
    WorldTime(url: 'Pacific/Kiritimati', location: 'Pacific - Kiritimati'),
    WorldTime(url: 'Pacific/Kosrae', location: 'Pacific - Kosrae'),
    WorldTime(url: 'Pacific/Kwajalein', location: 'Pacific - Kwajalein'),
    WorldTime(url: 'Pacific/Majuro', location: 'Pacific - Majuro'),
    WorldTime(url: 'Pacific/Marquesas', location: 'Pacific - Marquesas'),
    WorldTime(url: 'Pacific/Nauru', location: 'Pacific - Nauru'),
    WorldTime(url: 'Pacific/Niue', location: 'Pacific - Niue'),
    WorldTime(url: 'Pacific/Norfolk', location: 'Pacific - Norfolk'),
    WorldTime(url: 'Pacific/Noumea', location: 'Pacific - Noumea'),
    WorldTime(url: 'Pacific/Pago_Pago', location: 'Pacific - Pago Pago'),
    WorldTime(url: 'Pacific/Palau', location: 'Pacific - Palau'),
    WorldTime(url: 'Pacific/Pitcairn', location: 'Pacific - Pitcairn'),
    WorldTime(url: 'Pacific/Pohnpei', location: 'Pacific - Pohnpei'),
    WorldTime(url: 'Pacific/Port_Moresby', location: 'Pacific - Port Moresby'),
    WorldTime(url: 'Pacific/Rarotonga', location: 'Pacific - Rarotonga'),
    WorldTime(url: 'Pacific/Tahiti', location: 'Pacific - Tahiti'),
    WorldTime(url: 'Pacific/Tarawa', location: 'Pacific - Tarawa'),
    WorldTime(url: 'Pacific/Tongatapu', location: 'Pacific - Tongatapu'),
    WorldTime(url: 'Pacific/Wake', location: 'Pacific - Wake'),
    WorldTime(url: 'Pacific/Wallis', location: 'Pacific - Wallis')
  ];

  void updateTime(index) async{
    WorldTime instance = locations[index];
    await instance.getTime();
    // navigate to HomeScreen
    Navigator.pop(context, {
      'location' : instance.location,
      'time' : instance.time,
      'isDayTime' : instance.isDayTime,
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey[700],

      appBar: AppBar(
        backgroundColor: Colors.grey[900],

        title: Text(
          'Select a Location',
          style: TextStyle(
            fontFamily: 'Montserrat',
            fontSize: 24,
         )
        ),
        centerTitle: true,
        elevation: 0,
      ),

      body: ListView.builder(
        itemCount: locations.length,
        itemBuilder: (context, index) {
          return Card(

            child: ListTile(
              onTap: () {
                updateTime(index);
              },
              title: Text(
                  locations[index].location,
              ),
            ),
          );
        },
      ),
    );
  }
}